### ISSUE TITLE
Provide general provider-specific configuration in cloud profile

### ISSUE THREAD

**Issue by Gerrit91** [metal-pod/gardener-extension-provider-metal#25]
To enhance validations, reduce the complexity of the shoot spec and simplify the integration of the metal provider into the Gardener dashboard, we need to provide some provider config into the cloud profile:

- [x] Add control plane IAM config into cloud profile
  - [x] Populate control plane deployment charts dynamically with the values from the cloud profile
  - [x] Still allow overriding these cloud defaults with the existing shoot iam provider config spec
  - [x] Validate shoot spec by checking against cloud profile as well (allow them to be unset in shoot spec)
- [x] Add available firewall images to cloud profile and add to validation
- [x] Add available firewall networks to cloud profile and add to validation

**Comment by Gerrit91** [comment]
Proposal for cloud profile spec:

```
---
apiVersion: core.gardener.cloud/v1alpha1
kind: CloudProfile
metadata:
  name: metal
spec:
  type: metal
  providerConfig:
    apiVersion: metal.provider.extensions.gardener.cloud/v1alpha1
    kind: CloudProfileConfig
    iamconfig:
      groupConfig:
        namespaceMaxLength: 20
      idmConfig:
        idmtype: UX
      issuerConfig:
        clientId: auth-go-cli
        url: <dex-url>
    firewallImages:
      - firewall-1
    firewallNetworks:
       <partition-a>:
        internet: <partition-a-internet-network-id>
       <partition-b>:
        internet: <partition-b-internet-network-id>
```
