### ISSUE TITLE
Internal version used for `infrastructureStatus`

### ISSUE THREAD

**Issue by rfranzke** [metal-pod/gardener-extension-provider-metal#28]
The `InfrastructureStatus` is used with the internal API version, e.g.

```
infrastructureProviderStatus:
      Firewall:
        MachineID: metal:///...
        Succeeded: true
      apiVersion: metal.provider.extensions.gardener.cloud/__internal
      kind: InfrastructureStatus
```

Instead, a version (e.g., `v1alpha1` should be used) as this information is client-facing.
