### ISSUE TITLE
ControlPlane controller complains after latest changes if no providerConfig is given

### ISSUE THREAD

**Issue by rfranzke** [metal-pod/gardener-extension-provider-metal#29]
With the latest changes, the `iamconfig` is part of the `CloudProfileConfig`. I assumed that you can now leave `controlPlaneConfig` in `Shoot` resources empty, but then the ControlPlane controller complains with:

```yaml
    lastOperation:
      description: 'Error reconciling controlplane: provider config is not set on
        the control plane resource'
```

After specifying

```yaml
controlPlaneConfig:
  apiVersion: metal.provider.extensions.gardener.cloud/v1alpha1
  kind: ControlPlaneConfig
```

it could successfully reconcile. It would be nicer if `controlPlaneConfig` would be completely optional now.
